// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sigis.Infrastructure.Persistence.Context;

#nullable disable

namespace Sigis.Infrastructure.Migrations
{
    [DbContext(typeof(SigisDbContext))]
    [Migration("20260917021149_AddCoverageEntities")]
    partial class AddCoverageEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sigis")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sigis.Domain.Entities.AccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("justification");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("legal_basis");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_agent");

                    b.Property<bool>("_isCrossUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cross_unit");

                    b.HasKey("Id")
                        .HasName("pk_access_log");

                    b.HasIndex("DateTime")
                        .HasDatabaseName("idx_access_log_date");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_access_log_person");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("idx_access_log_professional");

                    b.ToTable("access_log", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<string>("FormData")
                        .HasMaxLength(500)
                        .HasColumnType("jsonb")
                        .HasColumnName("form_data");

                    b.Property<string>("MainComplaint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("main_complaint");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("session_number");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("session_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TriagedByProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("triaged_by_professional_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("idx_attendance_professional");

                    b.HasIndex("TriagedByProfessionalId")
                        .HasDatabaseName("idx_attendance_triaged_by");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("idx_attendance_unit");

                    b.HasIndex("PersonId", "DateTime")
                        .HasDatabaseName("idx_attendance_person_date");

                    b.ToTable("attendance", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.ConcurrentTreatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("ProfessionalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("professional_name");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_concurrent_treatment");

                    b.HasIndex("PersonId", "DayOfWeek")
                        .HasDatabaseName("idx_concurrent_treatment_person");

                    b.ToTable("concurrent_treatment", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.DevelopmentMilestones", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AgeTalkedMonths")
                        .HasColumnType("integer")
                        .HasColumnName("age_talked_months");

                    b.Property<int?>("AgeWalkedMonths")
                        .HasColumnType("integer")
                        .HasColumnName("age_walked_months");

                    b.Property<string>("CommandComprehension")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("command_comprehension");

                    b.Property<string>("CommunicationForm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("communication_form");

                    b.Property<bool?>("CoordinationDifficulty")
                        .HasColumnType("boolean")
                        .HasColumnName("coordination_difficulty");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("HearingDifficulty")
                        .HasColumnType("boolean")
                        .HasColumnName("hearing_difficulty");

                    b.Property<bool?>("LocomotionDifficulty")
                        .HasColumnType("boolean")
                        .HasColumnName("locomotion_difficulty");

                    b.Property<string>("ManualDominance")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("manual_dominance");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("SpeechProblems")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("speech_problems");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("VisualDifficulty")
                        .HasColumnType("boolean")
                        .HasColumnName("visual_difficulty");

                    b.HasKey("Id")
                        .HasName("pk_development_milestones");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_development_milestones_person");

                    b.ToTable("development_milestones", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.DuplicateAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonId1")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id_1");

                    b.Property<Guid>("PersonId2")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id_2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_professional_id");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_duplicate_alert");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_duplicate_alert_status");

                    b.HasIndex("PersonId1", "PersonId2")
                        .IsUnique()
                        .HasDatabaseName("idx_duplicate_alert_pair");

                    b.ToTable("duplicate_alert", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.FamilyComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AbortionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("abortions_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_type");

                    b.Property<string>("FatherEducation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("father_education");

                    b.Property<string>("FatherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("father_name");

                    b.Property<string>("FatherOccupation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("father_occupation");

                    b.Property<string>("FiliationType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("filiation_type");

                    b.Property<int?>("HouseholdMembersCount")
                        .HasColumnType("integer")
                        .HasColumnName("household_members_count");

                    b.Property<string>("MedicationDuringPregnancy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("medication_during_pregnancy");

                    b.Property<string>("MotherEducation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mother_education");

                    b.Property<string>("MotherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mother_name");

                    b.Property<string>("MotherOccupation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mother_occupation");

                    b.Property<string>("ParentsMaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parents_marital_status");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<bool?>("PlannedPregnancy")
                        .HasColumnType("boolean")
                        .HasColumnName("planned_pregnancy");

                    b.Property<int?>("PregnanciesCount")
                        .HasColumnType("integer")
                        .HasColumnName("pregnancies_count");

                    b.Property<string>("PregnancyHealthIssue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pregnancy_health_issue");

                    b.Property<string>("SiblingsAges")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("siblings_ages");

                    b.Property<int?>("SiblingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("siblings_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_family_composition");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_family_composition_person");

                    b.ToTable("family_composition", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cns")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cns");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relationship");

                    b.HasKey("Id")
                        .HasName("pk_guardian");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_guardian_person");

                    b.ToTable("guardian", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.LearningDifficulties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AssessmentDate")
                        .HasColumnType("date")
                        .HasColumnName("assessment_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_learning_difficulties");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_learning_difficulties_person");

                    b.HasIndex("PersonId", "Type")
                        .IsUnique()
                        .HasDatabaseName("idx_learning_difficulties_person_type");

                    b.ToTable("learning_difficulties", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("AttendsTutoring")
                        .HasColumnType("boolean")
                        .HasColumnName("attends_tutoring");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("ClassGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class_group");

                    b.Property<string>("Cns")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cns");

                    b.Property<string>("Cpf")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentSchool")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("current_school");

                    b.Property<string>("DisabilityTypes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("disability_types");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<bool?>("HasFailedGrade")
                        .HasColumnType("boolean")
                        .HasColumnName("has_failed_grade");

                    b.Property<string>("MotherName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("mother_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Naturality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("naturality");

                    b.Property<bool?>("NeedsSpecialEducation")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_special_education");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("RaceColor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("race_color");

                    b.Property<bool?>("ReferredBySchool")
                        .HasColumnType("boolean")
                        .HasColumnName("referred_by_school");

                    b.Property<string>("SchoolEnrollment")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("school_enrollment");

                    b.Property<string>("Shift")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shift");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Zone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("zone");

                    b.Property<string>("name_normalized")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("name_normalized")
                        .HasComputedColumnSql("sigis.immutable_unaccent(lower(name))", true);

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("BirthDate")
                        .HasDatabaseName("idx_person_birth_date");

                    b.HasIndex("Cns")
                        .IsUnique()
                        .HasDatabaseName("idx_person_cns")
                        .HasFilter("cns IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("idx_person_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("name_normalized")
                        .HasDatabaseName("idx_person_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("name_normalized"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("name_normalized"), new[] { "gin_trgm_ops" });

                    b.ToTable("person", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.PersonClinicalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApsReferenceUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("aps_reference_unit_id");

                    b.Property<string>("ClinicalHypothesis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("clinical_hypothesis");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MedicalRecordNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("medical_record_number");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_person_clinical_profile");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_person_clinical_profile_person");

                    b.HasIndex("ApsReferenceUnitId", "MedicalRecordNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_person_clinical_profile_record_unique")
                        .HasFilter("medical_record_number IS NOT NULL");

                    b.ToTable("person_clinical_profile", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.PersonConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("evidence");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedByGuardianId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_guardian_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_person_consent");

                    b.HasIndex("GrantedByGuardianId")
                        .HasDatabaseName("ix_person_consent_granted_by_guardian_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_person_consent_person");

                    b.HasIndex("PersonId", "Type")
                        .IsUnique()
                        .HasDatabaseName("idx_person_consent_active_unique")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("person_consent", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_professional");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_professional_email");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("idx_professional_unit");

                    b.ToTable("professional", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveAbsences")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_absences");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_queue_entry");

                    b.HasIndex("PersonId", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("idx_queue_active_unique")
                        .HasFilter("status IN ('Waiting', 'InAttendance')");

                    b.HasIndex("UnitId", "Status")
                        .HasDatabaseName("idx_queue_unit_status");

                    b.ToTable("queue_entry", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DestinationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_unit_id");

                    b.Property<Guid>("OriginUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_unit_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReferralDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("referral_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_referral");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("idx_referral_correlation");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_referral_person");

                    b.HasIndex("DestinationUnitId", "Status")
                        .HasDatabaseName("idx_referral_destination_status");

                    b.ToTable("referral", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.SchoolHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class_group");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_professional_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("school_name");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer")
                        .HasColumnName("school_year");

                    b.Property<string>("Shift")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shift");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_school_history");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_school_history_active_unique")
                        .HasFilter("status = 'Ativo'");

                    b.HasIndex("PersonId", "SchoolYear")
                        .HasDatabaseName("idx_school_history_person");

                    b.ToTable("school_history", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.ServiceUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acronym");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Secretariat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("secretariat");

                    b.HasKey("Id")
                        .HasName("pk_service_unit");

                    b.HasIndex("Acronym")
                        .IsUnique()
                        .HasDatabaseName("idx_service_unit_acronym");

                    b.ToTable("service_unit", "sigis");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.ConcurrentTreatment", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_concurrent_treatment_person_person_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.DevelopmentMilestones", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_development_milestones_person_person_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.FamilyComposition", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_composition_person_person_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Guardian", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.Person", null)
                        .WithMany("Guardians")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guardian_person_person_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.LearningDifficulties", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_difficulties_person_person_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Person", b =>
                {
                    b.OwnsOne("Sigis.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("zip_code");

                            b1.HasKey("PersonId");

                            b1.ToTable("person", "sigis");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_person_person_id");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.PersonClinicalProfile", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.ServiceUnit", null)
                        .WithMany()
                        .HasForeignKey("ApsReferenceUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_person_clinical_profile_service_unit_aps_reference_unit_id");

                    b.HasOne("Sigis.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_clinical_profile_person_person_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.PersonConsent", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.Guardian", null)
                        .WithMany()
                        .HasForeignKey("GrantedByGuardianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_person_consent_guardian_granted_by_guardian_id");

                    b.HasOne("Sigis.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_consent_person_person_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Professional", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.ServiceUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_professional_service_unit_unit_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.SchoolHistory", b =>
                {
                    b.HasOne("Sigis.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_school_history_person_person_id");
                });

            modelBuilder.Entity("Sigis.Domain.Entities.Person", b =>
                {
                    b.Navigation("Guardians");
                });
#pragma warning restore 612, 618
        }
    }
}
